run: compile
	java FrontEndWisconsinMap

compile:
	javac CS400Graph.java
	javac Cities.java
	javac CitiesBackEnd.java
	javac FrontEndWisconsinMap.java

test:
	@echo "FIXME: *test* should run all your group's testing engineer's JUnit tests for the application"

clean:
	$(RM) *.class
